<div class="content">
    <span>Termeni si Conditii Will</span></br>
    
    Pagina termeni si conditii Director Web


Va rugam sa cititi aceste instructiuni si sa respectati toate criteriile si indrumarile inainte de a adauga siteul dvs. Editorii will.ro au dreptul sa respinga, suspende sau sa stearga fara preaviz orice site care nu respecta instructiunile de mai jos sau instructiunile suplimentare aferente planurilor.

Inainte de a continua propunerea, verificati daca site-ul nu este deja listat in director.



  NU acceptam in director urmatoarele categorii de site-uri:
>site-uri gazduite gratuit si/sau subdomenii gratuite;
>site-uri duplicat (mirror);
>site-uri in constructie sau cu pagini fara continut;
>site-uri in alta limba decat romana/engleza 
>site-uri cu publicitate excesiva;
>site-uri care contin cuvinte ascunse sau orice forma de spam etc;
>site-uri care incalca orice lege romaneasca sau internationala; 
>site-uri care deschid pop-up, pop-under sau impun votul in diverse topuri sau clasamente;
>site-uri care redirectioneaza catre alt domeniu;
>site-uri cu continut sau orientare sexuala si/sau fara avertismentele legale

Prin acceptarea acestor Termeni si Conditii, utilizatorul este de acord sa primeasca notificari din partea will.ro precum si informatii suplimentare din partea site-urilor partenere detinute de BlueBay Design S.R.L.
</div>