<div style="margin: 10px 0px;">
    <div id="line1"><span> will - director web</span>Web Design by <a id="bb" href="http://www.bluebay.ro" target="_blank">Blue Bay Design</a></div>
    <div id="line2"></div><br>
    <div style="text-align: center; line-height: 1.3 em; color: grey; font-weight: bold;">
        <?php foreach($this->getFooterLinks() as $f){
            echo $f->title.' &nbsp; ';
        } ?>
    </div>
</div>
