<div>
    <a href="<?php echo $this->url(array(        
        'controller' => 'index',
        'action' => 'index'
    ), 'default'); ?>" title="Will.ro - director Web" id="logo"></a>
    <a href="<?php echo $this->url(array(
        'controller' => 'linkuri',
        'action' => 'adauga-link'
    )); ?>" title="Adauga site-ul tau" id="add_site">
        <div>
            Adauga gratuit site-ul tau </br>
            <span>Will - director web</span>  
        </div>
    </a>
</div>