<div><?php echo $this->GetAds('nav_left')->adv_code ; ?>
    <ul>
        <li>
            <a href="<?php echo $this->baseUrl('/termeni'); ?>" >Termeni si conditii</a>
            <a href="<?php echo $this->baseUrl('/servicii'); ?>" >Servicii Will</a>
            <a href="<?php echo $this->baseUrl('/avantaje'); ?>" >Avantaje Director Web</a>
            <a href="<?php echo $this->baseUrl('/contact'); ?>" >Contact</a>
    </ul>
</div>