
<div class="menu-container">
    <div class="meteo"></div>
    <div class="bg">
        <h3></br><?php             
            echo strftime('%A %d.%m.%Y'); 
        ?></h3> 

        <?php 
        foreach ($this->getMeteo() as $m): ?>
        <div class="div1">
            <div>    
                <div style="display: inline-block; vertical-align: middle; width: 72%;">
                    <?php echo $m['city'] ?>
                </div>
                <div style="display: inline-block; vertical-align: middle; width: 25%; text-align: right;">
                    <?php echo $m['temp']; ?> &deg;C
                </div>
            </div>
        </div>

        <?php endforeach; ?>
        <div class="rb_btm"></div>
        <div class="clear"></div>
    </div>
</div>