<div>
    <ul>
        <li>
            <a href="<?php echo $this->baseUrl('/'); ?>" >Home</a>
            <a href="<?php echo $this->baseUrl('/categorii'); ?>" >Categorii</a>
            <a href="<?php echo $this->baseUrl('/adauga'); ?>" >Adauga link</a>
            <div id="search">
                <form action="http://www.google.ro/cse" id="cse-search-box" target="_blank">

                <input type="hidden" name="cx" value="partner-pub-7922830022766583:v6802u-fvih" /> 
                <input type="hidden" name="ie" value="ISO-8859-2" /> 
                <input type="text" name="q" size="31" /> 
                <input type="submit" name="sa" value="C&#x0103;utare" /> 

            </form> 
            <script type="text/javascript" src="http://www.google.ro/cse/brand?form=cse-search-box&amp;lang=ro"></script>
             
            </div>
           
         </li>
    </ul>
</div>