<div class="content">
    <h1 class="head1">Adauga Link in director</h1>
    <div style=" text-align: center">
        <label for="basic" style="padding: 5px; display: inline-block; vertical-align: top;">
            <div>
                <img src="/default/img/basic.jpg" alt="Link basic" title="Link basic" onclick="toggle('toggle', 0)">
            </div>
            
            <input type="radio" id="basic" name="linkType">
         
        </label>
        <label for="exchange" style="padding: 5px; display: inline-block; vertical-align: top;">
            <div>
                <img src="/default/img/link_exchange.jpg" alt="Link exchange" title="Schimb de link" onclick="toggle('toggle', 1)">
            </div>
            
            <input type="radio" id="exchange" name="linkType">
          
        </label>
    </div>
     
     
    
    <div id="toggle" style="display:none;">
        <p style="padding: 5px 0px 5px">Pentru a putea inregistra site-ul in reteaua de link-exchange, te rugam sa adaugi unul din linkurile urmatoare in pagina principala a siteului:</p>
        <p style="color:red; padding: 5px 0px 10px">Dupa verificare(maxim 24 ore), site-ul dumneavoastra va aparea pe primele pozitii in categoria din care face parte!</p>
        <p style="width: 37%; display: inline-block; vertical-align: middle; text-align: center;">will.ro - director online</p>
        <textarea name="as" rows="4" style="width: 60%; display: inline-block; vertical-align: middle; margin-left: -5px;"><a href="http://www.will.ro" title="Director web Will.ro" target="_blank">will.ro - director online</a></textarea>
        <p style="width: 37%; display: inline-block; vertical-align: middle; text-align: center;"><img src="/default/img/logo.jpg" alt="Director web Will.ro" border="0"></p>
        <textarea name="ass" rows="4" style="width: 60%; display: inline-block; vertical-align: middle; margin-left: -5px;"><a href="http://www.will.ro" title="Director web Will.ro" target="_blank"><img src="http://www.will.ro/logo.jpg" alt="Director web Will.ro" border="0"></a></textarea>
    </div>
    <p style="color:red; padding: 5px 0px 10px" id="switch">
        Site-urile vor fi validate in 72 ore si vor aparea pe site in ordinea introducerii.
    </p>
    <?php
        echo $this->form; 
    ?>
    
   
</div>

<script type="text/javascript">
    function toggle(toggle, value) {
	var ele = document.getElementById(toggle);
        var basics = document.getElementById('switch')
	
        if (value == "0") {
            ele.style.display = "none";
            basics.style.display = "block";
        } else {
            ele.style.display = "block";
            basics.style.display = "none";
        }
            
            document.getElementById('linkType').value = value;
    }
    document.getElementById('basic').checked = true;
</script>


<style>
    .errors input, .errors select, .errors textarea, .errors input[type="checkbox"]
    {
        border: solid 1px red;        
    }    
</style>