<div class="content">
    <div class="head1"><?php echo htmlspecialchars($this->link->title); ?></div>
    <div class="titluLink"><?php echo htmlspecialchars($this->link->title); ?></div>
    <div>
        <a class="url" href="<?php echo htmlspecialchars($this->link->url); ?>" target="_blank">
        <?php echo htmlspecialchars($this->link->url); ?>
        </a>
    </div>
    <div><?php echo htmlspecialchars($this->link->shortDescription); ?></div></br>
    <div><?php echo htmlspecialchars($this->link->longDescription); ?></div>
    
    <hr>
    <div>
        <div style="font-weight: bold; font-size: 1.2em;">Alte linkuri din aceeasi categorie :</div>
    
    <?php foreach ($this->linkuri as $listare): ?>
        <div class="linkuriplus">
            <a id="titlualtelinkuri"href="<?php echo $this->url(array(
                    'title' => $this->FormatUrl($listare->title),
                    'linkId' => $listare->id,        
                    ), 'detalii_link'); ?>"><?php echo htmlspecialchars($listare->title) ;?>
                </a>
            <br>
                <?php echo substr(htmlspecialchars($listare['shortDescription']), 0, 120); ?>
                <a href="<?php echo $this->url(array(
                    'title' => $this->FormatUrl($listare->title),
                    'linkId' => $listare->id,        
                ), 'detalii_link'); ?>">...mai mult! 
                </a>
        </div>
    <?php endforeach; ?>
    </div>
</div>