<div class="content">
    <div>
        <span><?php echo htmlspecialchars($this->link->category); ?></span> > 
            <?php echo htmlspecialchars($this->link->subcategory); ?>
    </div></br>
    <div><?php echo htmlspecialchars($this->link->title); ?></div>
    <div>
        <a href="<?php echo htmlspecialchars($this->link->url); ?>" target="_blank">
        <?php echo htmlspecialchars($this->link->url); ?>
        </a>
    </div>
    <div><?php echo htmlspecialchars($this->link->shortDescription); ?></div></br>
    <div><?php echo htmlspecialchars($this->link->longDescription); ?></div>
    
    <hr>
    <div>
        <div style="font-weight: bold; font-size: 1.2em;">Alte linkuri din aceeasi categorie :</div>
    
    <?php foreach ($this->linkuri as $listare): ?>
        <div id="linkuriplus">
                <a href="<?php echo $this->url(array(
                    'title' => $listare->title,
                    'linkId' => $listare->id,        
                    ), 'detalii_link'); ?>"><?php echo htmlspecialchars($listare->title) ;?><a/></br>
                <a class="short" href="<?php echo $this->url(array(
                    'title' => $listare->title,
                    'linkId' => $listare->id,        
                ), 'detalii_link'); ?>">
                    <?php echo substr(htmlspecialchars($listare['shortDescription']), 0, 120).'..'; ?>
        </div>
    <?php endforeach; ?>
    </div>
</div>