<div class="head1"><?php echo $this->cat ?> > <?php echo $this->subcat ?></div>
<div class="content">
   <?php foreach ($this->linkuri as $listare): ?>
    <div id="listare_linkuri">
        <ul>
            <li>
                <?php echo htmlspecialchars($listare['title']) ;?></br>
                <a id="url" href="<?php echo htmlspecialchars($listare->url); ?>" target="_blank">
                    <?php echo htmlspecialchars($listare['url']); ?>
                </a></br>
                <a id="short" href="<?php echo $this->url(array(
                    'title' => $listare->title,
                    'linkId' => $listare->id,        
                ), 'detalii_link'); ?>">
                    <?php echo htmlspecialchars($listare['shortDescription']); ?>
                </a></br>
            </li>           
        </ul>   
    </div>
    <?php endforeach; ?>
</div>

