<div class="head1"><a href="<?php echo $this->url(array(
                'category' => $this->FormatUrl($this->category->categoryName),
                'categoryId' => $this->category->parentId,        
                ), 'listare_subcategorii');  ?>"><?php echo $this->category->categoryName; ?></a> > 
                    <?php echo $this->category->category ?>
</div>
<div class="content">
    
   <?php $i=1; foreach ($this->linkuri as $listare) : ?>
    <div class="listare_linkuri ">
        <ul style=" clear: both;">
            <li><img src="<?php echo $this->baseUrl($this->FileExist($listare['id'])); ?>" width="100" height="75" style="valign:top;float:left; padding:0px 5px 10px;"/>
                <span class="titluLink">
				
				<?php echo htmlspecialchars($listare['title']) ;?><?php if ($listare->type == 'exchange'){
                 echo '<img src="/default/img/sponsor.jpg" width="39px" height="12px">'; } ?>
                </span></br>
                <a class="url" href="<?php echo htmlspecialchars($listare->url); ?>" target="_blank">
                    <?php echo htmlspecialchars($listare['url']); ?>
                </a></br>
                <a class="short" href="<?php echo $this->url(array(
                    'title' => $this->FormatUrl($listare->title),
                    'linkId' => $listare->id,        
                ), 'detalii_link'); ?>">
                    <?php echo htmlspecialchars($listare['shortDescription']); ?>
                </a></br>
            </li>           
        </ul>   
    </div>
    <?php if( ($this->maxPePag / 2) == $i) : ?>
    <div class="listare_linkuri">
        <ul>
            <li>
                <?php echo $this->GetAds('links')->adv_code; ?>
            </li>           
        </ul>   
    </div>
    <?php endif; ?>
    <?php $i++; endforeach; ?>
</div>


<?php

$rOffset = 3; 
$i = $this->currPage-$rOffset;

if($i<=0) {
    $i = 1;
    $rOffset = ($rOffset*2 - @$_GET['pag']) + 1;
}
elseif( $_GET['pag'] > $this->nrPagini-$rOffset && $i>$rOffset) {
    $i = $i - $rOffset + ($this->nrPagini - $_GET['pag']);
}



for($i; $i <= $this->currPage+$rOffset && $i<= $this->nrPagini; $i++): ?>

<a href="?pag=<?php echo $i; ?>"
   style="border-radius: 3px; border: solid 1px black; display: inline-block; padding: 5px; <?php if($_GET['pag'] == $i) echo 'border: solid 1px red;'; ?>">
    <?php echo $i; ?>
</a>


<?php endfor; ?>


