<div class="content">
    <div class="head1"><?php echo htmlspecialchars($this->info->title); ?></div>
    <div class="titluLink"><?php echo htmlspecialchars($this->info->title); ?></div>
    <div>
        <a class="url" href="<?php echo htmlspecialchars($this->info->url); ?>" target="_blank">
        <?php echo htmlspecialchars($this->info->url); ?>
        </a>
    </div>
    <div><?php echo htmlspecialchars($this->info->desc); ?></div></br>

    
    <hr>
    <div>
        <div style="font-weight: bold; font-size: 1.2em;">Alte linkuri din aceeasi categorie :</div>

        <?php foreach ($this->sponsor as $s): ?>
                <div class="linkuriplus">
                    <a id="titlualtelinkuri" href="<?php echo $this->url(array(
                            'title' => $this->FormatUrl($s->title),
                            'id' => $s->id,        
                            ), 'sponsor_link'); ?>">
                                <?php echo htmlspecialchars($s->title) ;?>
                        </a><img src="/default/img/sponsor.jpg" width="39px" height="12px">
                    <br>
                         <?php echo htmlspecialchars($s['desc']); ?>
                        <a class="short" href="<?php echo $this->url(array(
                            'title' => $this->FormatUrl($s->title),
                            'id' => $s->id,        
                        ), 'sponsor_link'); ?>">
                            ...mai mult!
                </div>
        <?php endforeach; ?>
    </div>
</div>