<div>
    <h1 class="head1">Ultimele adaugate in director web</h1>
    <div>
        <?php foreach ($this->lastLinks as $l): ?>
        
        <?php   echo htmlspecialchars($l->url); ?></br>
         
        <?php endforeach; ?>
    </div><br><br>
    <h1 class="head1">Legaturi sponsorizate Will</h1>
    
    <div>
        <?php foreach ($this->promoLinks as $p): ?> 
        
        <?php echo htmlspecialchars($p->title).'<img src="/default/img/sponsor.jpg" width="39px" height="17px">'.'</br>'; ?>

        <a href="<?php echo 'http://'.htmlspecialchars($p->url); ?>" target="_blank">
            <?php echo htmlspecialchars($p->url); ?>
        </a></br>
        <a href="<?php echo  $this->url(array(
                    'title' => $p->title,
                    'id' => $p->id,        
                ), 'sponsor_link'); ?>">
            <?php echo htmlspecialchars($p->desc); ?>
        </a></br>

        
        <?php endforeach; ?>
    </div>
</div>

