<div class="container">
     <?php echo $this->render('flash-messenger.phtml'); ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                <span class="btn btn-info btn-sm disabled">
                    Toate linkurile &nbsp; <span class="badge"><?php echo $this->totalLinks; ?></span>
                </span>
                </span></h3>
        </div>
        <div class="panel-body">
              <div class="list-group">
                <?php foreach ($this->listObj as $links) : ?>
                  <li class="list-group-item">
                    <h4 class="list-group-item-heading">
                        <a href="<?php echo $this->url(array('linkId' => $links->id), 'viewLink'); ?>">
                            <?php echo htmlspecialchars($links->title); ?>
                        </a>
                        <span class="label label-info pull-right">
                            <?php echo $links->type; ?>
                        </span></h4>
                    <p class="list-group-item-text">
                        <small><?php echo htmlspecialchars($links->url); ?> &nbsp; 
                        </small>
                        <a href="<?php echo $this->url(array('linkId' => $links->id), 'editLink'); ?>"><i class="glyphicon glyphicon-pencil text-info"></i></a> &nbsp; 
                        <a href="<?php echo $this->url(array('linkId' => $links->id), 'delLink'); ?>" onclick="return( confirm('Esti sigur ca vrei sa stergi acest link?'))">
                            <i class="glyphicon glyphicon glyphicon-remove text-danger"></i></a> &nbsp; 
                        <span class="text-muted" data-toggle="tooltip" data-placement="right" data-original-title="<?php echo ' e-Mail:'.htmlspecialchars($links->email).' IP:'.$links->ip; ?>">
                            <i class="glyphicon glyphicon-info-sign"></i>  &nbsp; 
                        </span>
                        
                        
                    <br /><?php echo htmlspecialchars(substr($links->shortDescription, 0, 150)).'..'; ?></p>
                  </li>
                <?php endforeach; ?>
              </div>
            
<?php

$rOffset = 3; 
$i = $this->currPage-$rOffset;

if($i<=0) {
    $i = 1;
    $rOffset = ($rOffset*2 - @$_GET['pag']) + 1;
}
elseif( $_GET['pag'] > $this->nrPagini-$rOffset && $i>$rOffset) {
    $i = $i - $rOffset + ($this->nrPagini - $_GET['pag']);
}



for($i; $i <= $this->currPage+$rOffset && $i<= $this->nrPagini; $i++): ?>

<a href="?pag=<?php echo $i; ?>"
   style="border-radius: 3px; border: solid 1px black; display: inline-block; padding: 5px; <?php if($_GET['pag'] == $i) echo 'border: solid 1px red;'; ?>">
    <?php echo $i; ?>
</a>


<?php endfor; ?>
            
        </div>
    </div>
</div>
